### ISSUE TITLE
To-do list for 0.3.4.0

### ISSUE THREAD

**Issue by hibiyasleep** [hibiyasleep/OverlayPlugin#22]
* [ ] Implement log filter on LogParse
* [ ] Fix tab corruption
* [ ] (to be added)
